name: example_code
description: This is an example code.
author: gzlock <gzlock88@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
