name: draggable_container
description:
  A Very Smooth Draggable Widget Container.
  Each children is Draggable, Deletable and Fixable.
  Support SliverGridDelegate!
version: 1.0.4+1
homepage: https://github.com/gzlock/flutter_draggable_container
repository: https://github.com/gzlock/flutter_draggable_container

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
