name: draggable_container
description: A Draggable Widget Container.
version: 0.0.1
author: gzlock <gzlock88@gmail.com>
homepage: https://github.com/gzlock/flutter_draggable_container
repository: https://github.com/gzlock/flutter_draggable_container

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter